// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWDxvRNJBx5tkq3sa_C2_N3yWnkQjvhQs',
    appId: '1:107047291062:web:48d32132d3a4cac426fe17',
    messagingSenderId: '107047291062',
    projectId: 'therophonobot-d22eb',
    authDomain: 'therophonobot-d22eb.firebaseapp.com',
    storageBucket: 'therophonobot-d22eb.firebasestorage.app',
    measurementId: 'G-D7F36DHBCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNkn8wDEaeiRReYMBn9OwMfm0hfeGE5pc',
    appId: '1:107047291062:android:c342a798ef516cf126fe17',
    messagingSenderId: '107047291062',
    projectId: 'therophonobot-d22eb',
    storageBucket: 'therophonobot-d22eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVfcAMgbruS_LZonv_rbjYaAEP0pyZ8-Q',
    appId: '1:107047291062:ios:46e907f05d985cbe26fe17',
    messagingSenderId: '107047291062',
    projectId: 'therophonobot-d22eb',
    storageBucket: 'therophonobot-d22eb.firebasestorage.app',
    androidClientId: '107047291062-l8q9ejclnn5rgi29ap4nbl7ji3msdaus.apps.googleusercontent.com',
    iosClientId: '107047291062-a0j1d30kvo8c28ou8s4hbdk3n908e8oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminTherophonobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVfcAMgbruS_LZonv_rbjYaAEP0pyZ8-Q',
    appId: '1:107047291062:ios:46e907f05d985cbe26fe17',
    messagingSenderId: '107047291062',
    projectId: 'therophonobot-d22eb',
    storageBucket: 'therophonobot-d22eb.firebasestorage.app',
    androidClientId: '107047291062-l8q9ejclnn5rgi29ap4nbl7ji3msdaus.apps.googleusercontent.com',
    iosClientId: '107047291062-a0j1d30kvo8c28ou8s4hbdk3n908e8oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminTherophonobot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWDxvRNJBx5tkq3sa_C2_N3yWnkQjvhQs',
    appId: '1:107047291062:web:5701973cfc43c50026fe17',
    messagingSenderId: '107047291062',
    projectId: 'therophonobot-d22eb',
    authDomain: 'therophonobot-d22eb.firebaseapp.com',
    storageBucket: 'therophonobot-d22eb.firebasestorage.app',
    measurementId: 'G-7HZ0D5JWCC',
  );
}
